#!/bin/bash

set -eu

ROOT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)

cd "$ROOT_DIR"
./bin/tree-sitter-stack-graphs test \
                               -P \
                               -V \
                               --output-mode always \
                               --grammar . \
                               --tsg queries/stack-graphs.tsg \
                               stack-graph-tests
